//! A model's command catalog: the names from the ROM's libraries
//! ([`crate::names`]) with their library and command numbers, as
//! `data/commands/<model>.json`, and the ROM's menus that offer each one
//! ([`crate::menus`]).

use std::path::Path;

use anyhow::Result;
use saturnus::Model;
use saturnus_drive::session::Limits;
use saturnus_mcp::emulator::Emulator;
use serde::{Deserialize, Serialize};

use crate::names;

/// One command of the catalog.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Command {
    /// The name as the ROM prints it.
    pub name: String,
    /// Library and command numbers (`XLIB lib n`); some names have two
    /// (the alternate forms of `+`, `∂`, `∫`).
    pub xlib: Vec<[u32; 2]>,
    /// The ROM's menus that offer it (`MTH PARTS`; `MENU n` for a menu no
    /// key or submenu label names), from `saturnus-refgen menus`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub menus: Vec<String>,
}

/// A key that opens a root menu.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct MenuKey {
    /// The menu's number (`n MENU`).
    pub menu: u32,
    /// The key's legend (the label on the key or the shifted label above
    /// it), which names the menu.
    pub key: String,
}

/// A model's catalog file.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Catalog {
    /// `48sx`, `48gx` or `49g`.
    pub model: String,
    /// How the data was made.
    pub method: String,
    /// Which key opens which root menu, observed on the ROM
    /// (`saturnus-refgen menus`).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub menu_keys: Vec<MenuKey>,
    /// The commands in library and number order.
    pub commands: Vec<Command>,
}

/// What the catalog's `method` says.
pub(crate) const METHOD: &str = "Generated by saturnus-refgen from the ROM on the emulator: the names of \
                      every library's commands, read by decompiling XLIB names (the ROM's own \
                      name tables); the menus that offer each, from the ROM's menu definitions \
                      named by the keys that open them (saturnus-refgen menus).";

/// The model name as the tools take it.
pub fn model_name(model: Model) -> &'static str {
    match model {
        Model::Hp48sx => "48sx",
        Model::Hp48gx => "48gx",
        Model::Hp49g => "49g",
        Model::Hp38g => "38g",
        Model::Hp39g => "39g",
        Model::Hp40g => "40g",
        Model::Hp42s => "42s",
    }
}

/// Boot `model` with a Kermit link whose exchanges do not depend on the
/// host's speed, so every run of the generators is the same.
pub fn boot(model: Model, rom: &Path) -> Result<Emulator> {
    let (mut emu, _) = Emulator::boot(model, rom, false, Limits::default())?;
    emu.set_deterministic_link(true);
    Ok(emu)
}

/// Build the catalog of `model` from the ROM at `rom`.
pub fn generate(model: Model, rom: &Path) -> Result<Catalog> {
    let mut emu = boot(model, rom)?;
    emu.start_server()?;
    let entries = names::extract(&mut emu)?;
    emu.stop_server()?;
    Ok(assemble(model, &entries))
}

/// One entry per name, with every number it has.
fn assemble(model: Model, entries: &[names::Entry]) -> Catalog {
    let mut commands: Vec<Command> = Vec::new();
    for e in entries {
        match commands.iter_mut().find(|c| c.name == e.name) {
            Some(c) => c.xlib.push([e.lib, e.number]),
            None => commands.push(Command {
                name: e.name.clone(),
                xlib: vec![[e.lib, e.number]],
                menus: Vec::new(),
            }),
        }
    }
    Catalog {
        model: model_name(model).to_string(),
        method: METHOD.to_string(),
        menu_keys: Vec::new(),
        commands,
    }
}

/// The catalog as the file holds it: pretty JSON and a final newline.
pub fn to_file_text(catalog: &Catalog) -> Result<String> {
    Ok(serde_json::to_string_pretty(catalog)? + "\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn names_with_two_numbers_are_one_entry() {
        let entry = |number, name: &str| names::Entry {
            lib: 2,
            number,
            name: name.into(),
        };
        let cat = assemble(
            Model::Hp48sx,
            &[entry(0, "ABS"), entry(1, "SINH"), entry(2, "ABS")],
        );
        assert_eq!(cat.model, "48sx");
        assert_eq!(cat.commands.len(), 2);
        assert_eq!(cat.commands[0].xlib, [[2, 0], [2, 2]]);
        assert_eq!(cat.commands[1].name, "SINH");
    }
}
