//! A model's command catalog: the names from the ROM's libraries
//! ([`crate::names`]) with the menus they appear in ([`crate::menus`]),
//! as `data/commands/<model>.json`.

use std::collections::{BTreeMap, VecDeque};
use std::path::Path;

use anyhow::Result;
use saturnus::Model;
use saturnus_drive::session::Limits;
use saturnus_mcp::emulator::Emulator;
use serde::{Deserialize, Serialize};

use crate::menus::{self, Crawler, Font, Menu};
use crate::names;

/// The category of commands typed by a keyboard key rather than a menu.
pub const KEYBOARD: &str = "Keyboard";
/// Menu numbers crawled: 0, 1 and 2 are the last menu, VAR and CST.
const MENUS: std::ops::RangeInclusive<u32> = 3..=255;

/// One command of the catalog.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Command {
    /// The name as the ROM prints it.
    pub name: String,
    /// Library and command numbers (`XLIB lib n`); some names have two
    /// (the alternate forms of `+`, `∂`, `∫`).
    pub xlib: Vec<[u32; 2]>,
    /// The first menu (in breadth-first order from the keyboard) that
    /// offers the command, as its key path, e.g. `MTH PARTS`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    /// Every menu that offers it.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub menus: Vec<String>,
}

/// One crawled menu.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct MenuEntry {
    /// The `MENU` number.
    pub number: u32,
    /// Key path from the keyboard, or `MENU n` when no key leads there.
    pub path: String,
    /// The labels of each page (`""` for an empty key).
    pub pages: Vec<Vec<String>>,
    /// Why the keys could not be pressed (commands then come from labels
    /// that spell a command name).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// A model's catalog file.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Catalog {
    /// `48sx`, `48gx` or `49g`.
    pub model: String,
    /// How the data was made.
    pub method: String,
    /// The commands in library and number order.
    pub commands: Vec<Command>,
    /// The menus in number order.
    pub menus: Vec<MenuEntry>,
}

/// What the catalog's `method` says.
const METHOD: &str = "Generated by saturnus-refgen from the ROM on the emulator: names by \
                      decompiling XLIB names of every library (the ROM's own name tables), \
                      menus by showing each MENU number, pressing its keys in program entry \
                      mode and following submenu keys; root menus are named after the \
                      keyboard key that shows them.";

/// The model name as the tools take it.
pub fn model_name(model: Model) -> &'static str {
    match model {
        Model::Hp48sx => "48sx",
        Model::Hp48gx => "48gx",
        Model::Hp49g => "49g",
        Model::Hp38g => "38g",
        Model::Hp39g => "39g",
        Model::Hp40g => "40g",
        Model::Hp42s => "42s",
    }
}

/// Whether `label` names a function printed on the keyboard that may
/// show a menu (words, not digits or symbols).
fn menu_like(label: &str) -> bool {
    label.len() >= 2
        && label
            .chars()
            .all(|c| c.is_ascii_uppercase() || c == '/' || c == ' ')
}

/// Keyboard keys that show a menu: `(menu, label)` from pressing each
/// worded key (plain, left-shifted, right-shifted) on a fresh copy of the
/// state and matching the labels shown against the crawled menus' first
/// pages.
fn root_keys(
    emu: &mut Emulator,
    font: &Font,
    menus: &[Menu],
    state: &Path,
) -> Result<Vec<(u32, String)>> {
    let skin = saturnus_web::skins::skin(emu.model());
    let mut out = Vec::new();
    for key in skin.keys {
        let tries = [
            ("", key.label),
            ("leftshift ", key.left),
            ("rightshift ", key.right),
        ];
        for (shift, label) in tries {
            if !menu_like(label) {
                continue;
            }
            emu.load_state(state)?;
            emu.press_keys(&format!("{shift}{}", key.name))?;
            let (screen, _) = emu.screen_text()?;
            let shown: Vec<String> = menus::read_labels(&screen)?
                .iter()
                .map(|l| font.read(l))
                .collect();
            if let Some(m) = menus
                .iter()
                .find(|m| m.pages.first().is_some_and(|p| p.labels == shown))
                && !out.iter().any(|(n, _)| *n == m.number)
            {
                out.push((m.number, label.to_string()));
            }
        }
    }
    Ok(out)
}

/// Keys that cannot type a command in program entry mode, or that would
/// disturb it.
const NOT_TYPING: [&str; 12] = [
    "on",
    "alpha",
    "leftshift",
    "rightshift",
    "shift",
    "enter",
    "backspace",
    "a",
    "b",
    "c",
    "d",
    "e",
];

/// The key scripts tried on the keyboard: every key unshifted (except
/// digits, arrows and editing keys) and both shifts.
fn keyboard_scripts(model: Model) -> Vec<String> {
    let skin = saturnus_web::skins::skin(model);
    let mut out = Vec::new();
    for key in skin.keys {
        if NOT_TYPING.contains(&key.name) || key.name == "f" {
            continue;
        }
        let plain_types = !matches!(
            key.name,
            "up" | "down" | "left" | "right" | "del" | "nxt" | "point" | "space" | "eex"
        ) && !key.name.chars().all(|c| c.is_ascii_digit());
        if plain_types {
            out.push(key.name.to_string());
        }
        out.push(format!("leftshift {}", key.name));
        out.push(format!("rightshift {}", key.name));
    }
    out
}

/// Name every menu by its key path, breadth first from the roots; the
/// order of the result is the discovery order.
fn paths(menus: &[Menu], roots: &[(u32, String)]) -> Vec<(u32, String)> {
    let by_number: BTreeMap<u32, &Menu> = menus.iter().map(|m| (m.number, m)).collect();
    let mut named: Vec<(u32, String)> = Vec::new();
    let mut queue: VecDeque<(u32, String)> = roots.iter().cloned().collect();
    while let Some((n, path)) = queue.pop_front() {
        if named.iter().any(|(m, _)| *m == n) {
            continue;
        }
        named.push((n, path.clone()));
        if let Some(menu) = by_number.get(&n) {
            for page in &menu.pages {
                for sub in &page.submenus {
                    if let Some(t) = sub.target {
                        queue.push_back((t, format!("{path} {}", sub.label)));
                    }
                }
            }
        }
    }
    for m in menus {
        if !named.iter().any(|(n, _)| *n == m.number) {
            named.push((m.number, format!("MENU {}", m.number)));
        }
    }
    named
}

/// Boot `model` with a Kermit link whose exchanges do not depend on the
/// host's speed, so every run of the generators is the same.
pub fn boot(model: Model, rom: &Path) -> Result<Emulator> {
    let (mut emu, _) = Emulator::boot(model, rom, false, Limits::default())?;
    emu.set_deterministic_link(true);
    Ok(emu)
}

/// Build the catalog of `model` from the ROM at `rom`.
pub fn generate(model: Model, rom: &Path) -> Result<Catalog> {
    let mut emu = boot(model, rom)?;
    emu.start_server()?;
    let entries = names::extract(&mut emu)?;
    emu.stop_server()?;
    if model == Model::Hp49g {
        // RPN entry and soft menus instead of choose boxes.
        emu.start_server()?;
        emu.run_command("-95. CF -117. SF")?;
        emu.stop_server()?;
    }
    let font = menus::build_font(&mut emu)?;
    let state = std::env::temp_dir().join(format!(
        "saturnus-refgen-{}-{}-roots.state",
        std::process::id(),
        model_name(model)
    ));
    let mut crawled = Vec::new();
    let keyboard;
    {
        let mut crawler = Crawler::new(&mut emu, &font)?;
        for n in MENUS {
            if let Some(m) = crawler.menu(n)? {
                crawled.push(m);
            }
        }
        let scripts = keyboard_scripts(model);
        keyboard = crawler
            .keyboard(&scripts)?
            .into_iter()
            .flatten()
            .collect::<Vec<String>>();
        crawler.save(&state)?;
    }
    let roots = root_keys(&mut emu, &font, &crawled, &state);
    // Best effort: a leftover file in the temporary directory.
    let _ = std::fs::remove_file(&state);
    let named = paths(&crawled, &roots?);
    Ok(assemble(model, &entries, &crawled, &named, &keyboard))
}

/// Put names, menus and paths together.
fn assemble(
    model: Model,
    entries: &[names::Entry],
    crawled: &[Menu],
    named: &[(u32, String)],
    keyboard: &[String],
) -> Catalog {
    let mut commands: Vec<Command> = Vec::new();
    for e in entries {
        match commands.iter_mut().find(|c| c.name == e.name) {
            Some(c) => c.xlib.push([e.lib, e.number]),
            None => commands.push(Command {
                name: e.name.clone(),
                xlib: vec![[e.lib, e.number]],
                category: None,
                menus: Vec::new(),
            }),
        }
    }
    let path_of = |n: u32| {
        named
            .iter()
            .find(|(m, _)| *m == n)
            .map_or_else(|| format!("MENU {n}"), |(_, p)| p.clone())
    };
    for (n, path) in named {
        let Some(menu) = crawled.iter().find(|m| m.number == *n) else {
            continue;
        };
        for page in &menu.pages {
            let words: Vec<&String> = if menu.error.is_some() {
                page.labels.iter().collect()
            } else {
                page.words.iter().collect()
            };
            for w in words {
                if let Some(c) = commands.iter_mut().find(|c| &c.name == w)
                    && !c.menus.contains(path)
                {
                    c.menus.push(path.clone());
                }
            }
        }
    }
    for w in keyboard {
        if let Some(c) = commands.iter_mut().find(|c| &c.name == w)
            && !c.menus.iter().any(|m| m == KEYBOARD)
        {
            c.menus.push(KEYBOARD.to_string());
        }
    }
    for c in &mut commands {
        c.category = c.menus.first().cloned();
    }
    let menus = crawled
        .iter()
        .map(|m| MenuEntry {
            number: m.number,
            path: path_of(m.number),
            pages: m.pages.iter().map(|p| p.labels.clone()).collect(),
            error: m.error.clone(),
        })
        .collect();
    Catalog {
        model: model_name(model).to_string(),
        method: METHOD.to_string(),
        commands,
        menus,
    }
}

/// The catalog as the file holds it: pretty JSON and a final newline.
pub fn to_file_text(catalog: &Catalog) -> Result<String> {
    Ok(serde_json::to_string_pretty(catalog)? + "\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::menus::{Page, Submenu};

    fn menu(number: u32, subs: &[(&str, u32)], words: &[&str]) -> Menu {
        Menu {
            number,
            pages: vec![Page {
                labels: Vec::new(),
                words: words.iter().map(|w| w.to_string()).collect(),
                submenus: subs
                    .iter()
                    .enumerate()
                    .map(|(key, (label, t))| Submenu {
                        key,
                        label: label.to_string(),
                        target: Some(*t),
                    })
                    .collect(),
            }],
            error: None,
        }
    }

    #[test]
    fn menus_are_named_by_key_path_breadth_first() {
        let menus = [
            menu(3, &[("PARTS", 4), ("HYP", 6)], &[]),
            menu(4, &[], &["ABS", "SIGN"]),
            menu(6, &[], &["SINH", "ABS"]),
            menu(9, &[], &["ODD"]),
        ];
        let named = paths(&menus, &[(3, "MTH".into())]);
        assert_eq!(
            named,
            [
                (3, "MTH".to_string()),
                (4, "MTH PARTS".to_string()),
                (6, "MTH HYP".to_string()),
                (9, "MENU 9".to_string())
            ]
        );
        let entries = [
            names::Entry {
                lib: 2,
                number: 0,
                name: "ABS".into(),
            },
            names::Entry {
                lib: 2,
                number: 1,
                name: "SINH".into(),
            },
            names::Entry {
                lib: 2,
                number: 2,
                name: "ABS".into(),
            },
            names::Entry {
                lib: 2,
                number: 3,
                name: "KEY".into(),
            },
        ];
        let cat = assemble(Model::Hp48sx, &entries, &menus, &named, &["KEY".into()]);
        assert_eq!(cat.commands.len(), 3);
        assert_eq!(cat.commands[0].xlib, [[2, 0], [2, 2]]);
        assert_eq!(cat.commands[0].category.as_deref(), Some("MTH PARTS"));
        assert_eq!(cat.commands[0].menus, ["MTH PARTS", "MTH HYP"]);
        assert_eq!(cat.commands[2].category.as_deref(), Some(KEYBOARD));
        assert!(menu_like("I/O") && menu_like("MTH") && !menu_like("7") && !menu_like("▲"));
    }
}
